name: Build FFmpeg Android ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config git wget tar automake autoconf libtool nasm

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
        unzip android-ndk-r26b-linux.zip
        export NDK=$PWD/android-ndk-r26b

    - name: Clone FFmpeg
      run: |
        git clone --depth=1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
        git checkout n7.0

    - name: Build FFmpeg
      run: |
        export NDK=$PWD/android-ndk-r26b
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export API=21
        export TARGET=aarch64-linux-android
        export PREFIX=$PWD/ffmpeg-build

        cd ffmpeg

        ./configure \
          --prefix=$PREFIX \
          --target-os=android \
          --arch=aarch64 \
          --cpu=armv8-a \
          --enable-cross-compile \
          --cross-prefix=$TOOLCHAIN/bin/$TARGET- \
          --cc=$TOOLCHAIN/bin/$TARGET$API-clang \
          --cxx=$TOOLCHAIN/bin/$TARGET$API-clang++ \
          --nm=$TOOLCHAIN/bin/$TARGET-nm \
          --sysroot=$TOOLCHAIN/sysroot \
          --disable-shared \
          --enable-static \
          --enable-gpl \
          --enable-nonfree \
          --enable-libx264 \
          --enable-libx265 \
          --enable-openssl \
          --enable-pic \
          --enable-neon \
          --enable-optimizations \
          --enable-encoder=aac \
          --enable-protocol=rtmp \
          --disable-doc \
          --disable-programs \
          --disable-avdevice \
          --disable-swresample \
          --disable-postproc \
          --disable-debug

        make -j$(nproc)
        make install

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-android-arm64
        path: ffmpeg-build
