name: Build FFmpeg 7 for Android ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FFmpeg Source
        uses: actions/checkout@v3
        with:
          repository: FFmpeg/FFmpeg
          ref: n7.0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git wget build-essential yasm nasm pkg-config \
            libx264-dev libx265-dev libfdk-aac-dev libopus-dev libvpx-dev \
            libass-dev libfreetype6-dev libmp3lame-dev libvorbis-dev

      - name: Clone Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
          unzip android-ndk-r26b-linux.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r26b

      - name: Configure FFmpeg for Android ARM64
        run: |
          export TOOLCHAIN=$PWD/android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64
          export API=21
          export TARGET=aarch64-linux-android
          export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
          export CXX=$TOOLCHAIN/bin/${TARGET}${API}-clang++

          ./configure \
            --prefix=$PWD/ffmpeg-android \
            --target-os=android \
            --arch=aarch64 \
            --cpu=armv8-a \
            --enable-cross-compile \
            --cross-prefix=$TOOLCHAIN/bin/${TARGET}- \
            --cc=$CC \
            --cxx=$CXX \
            --nm=$TOOLCHAIN/bin/llvm-nm \
            --ar=$TOOLCHAIN/bin/llvm-ar \
            --ranlib=$TOOLCHAIN/bin/llvm-ranlib \
            --strip=$TOOLCHAIN/bin/llvm-strip \
            --enable-gpl \
            --enable-nonfree \
            --enable-libx264 \
            --enable-libx265 \
            --enable-libfdk-aac \
            --enable-libopus \
            --enable-libvpx \
            --enable-libass \
            --enable-libmp3lame \
            --enable-libvorbis \
            --enable-libfreetype \
            --enable-openssl \
            --enable-avfilter \
            --enable-pic \
            --enable-static \
            --disable-shared \
            --enable-librtmp \
            --extra-cflags="-O3 -fPIC" \
            --extra-ldflags="-pie"

      - name: Build FFmpeg
        run: |
          make -j$(nproc)
          make install

      - name: Upload FFmpeg Build
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg7-android-arm64
          path: ffmpeg-android
