name: FFmpeg Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget make automake autoconf build-essential pkg-config libtool

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
        unzip android-ndk-r26b-linux.zip
        export NDK=$PWD/android-ndk-r26b

    - name: Clone FFmpeg
      run: |
        git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
        cd ffmpeg
        git checkout n6.1

    - name: Build FFmpeg for Android
      run: |
        export NDK=$PWD/android-ndk-r26b
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export API=21

        cd ffmpeg

        ./configure \
          --prefix=$PWD/build \
          --target-os=android \
          --arch=aarch64 \
          --cpu=armv8-a \
          --cross-prefix=$TOOLCHAIN/bin/aarch64-linux-android- \
          --cc=$TOOLCHAIN/bin/aarch64-linux-android$API-clang \
          --cxx=$TOOLCHAIN/bin/aarch64-linux-android$API-clang++ \
          --nm=$TOOLCHAIN/bin/aarch64-linux-android-nm \
          --sysroot=$TOOLCHAIN/sysroot \
          --enable-cross-compile \
          --enable-gpl \
          --enable-nonfree \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libfdk-aac \
          --enable-libmp3lame \
          --enable-libopus \
          --enable-libvpx \
          --enable-librtmp \
          --enable-openssl \
          --disable-debug \
          --disable-doc \
          --enable-static \
          --disable-shared \
          --enable-pic

        make -j$(nproc)
        make install

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-android-build
        path: ffmpeg/build
