name: Build FFmpeg for Android ARM64 without Subtitles

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout FFmpeg
      run: |
        git clone --depth=1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
        git checkout n7.0

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
        unzip android-ndk-r26b-linux.zip

    - name: Build FFmpeg
      run: |
        export NDK=$PWD/android-ndk-r26b
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export API=21

        export CC=$TOOLCHAIN/bin/aarch64-linux-android$API-clang
        export CXX=$TOOLCHAIN/bin/aarch64-linux-android$API-clang++
        export LD=$TOOLCHAIN/bin/aarch64-linux-android-ld
        export AR=$TOOLCHAIN/bin/aarch64-linux-android-ar
        export AS=$TOOLCHAIN/bin/aarch64-linux-android-as
        export NM=$TOOLCHAIN/bin/aarch64-linux-android-nm
        export STRIP=$TOOLCHAIN/bin/aarch64-linux-android-strip

        cd ffmpeg

        ./configure \
          --prefix=$PWD/build/arm64-v8a \
          --target-os=android \
          --arch=aarch64 \
          --cpu=armv8-a \
          --cross-prefix=$TOOLCHAIN/bin/aarch64-linux-android- \
          --cc=$CC \
          --cxx=$CXX \
          --nm=$NM \
          --strip=$STRIP \
          --enable-cross-compile \
          --enable-shared \
          --disable-static \
          --disable-doc \
          --disable-symver \
          --disable-debug \
          --enable-gpl \
          --enable-nonfree \
          --enable-openssl \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libfdk-aac \
          --enable-neon \
          --enable-mediacodec \
          --enable-libvpx \
          --enable-libopus \
          --enable-libvorbis \
          --enable-librtmp \
          --disable-libass \
          --disable-libfreetype \
          --disable-subtitles

        make -j$(nproc)
        make install

    - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-android-arm64
        path: ffmpeg/build/arm64-v8a
