name: Build FFmpeg for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential yasm pkg-config libtool git wget

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
        unzip android-ndk-r26b-linux.zip
        export NDK=$GITHUB_WORKSPACE/android-ndk-r26b

    - name: Clone FFmpeg
      run: |
        git clone --depth=1 --branch n7.0 https://git.ffmpeg.org/ffmpeg.git ffmpeg

    - name: Build FFmpeg
      run: |
        export NDK=$GITHUB_WORKSPACE/android-ndk-r26b
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        cd ffmpeg
        ./configure \
          --prefix=$GITHUB_WORKSPACE/ffmpeg-android-build \
          --enable-cross-compile \
          --cross-prefix=$TOOLCHAIN/bin/aarch64-linux-android- \
          --target-os=android \
          --arch=aarch64 \
          --sysroot=$TOOLCHAIN/sysroot \
          --cc=$TOOLCHAIN/bin/aarch64-linux-android21-clang \
          --cxx=$TOOLCHAIN/bin/aarch64-linux-android21-clang++ \
          --enable-shared \
          --enable-gpl \
          --enable-nonfree \
          --enable-libfdk_aac \
          --enable-libx264 \
          --enable-libx265 \
          --enable-openssl \
          --disable-doc \
          --disable-programs
        make -j$(nproc)
        make install

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-android-build
        path: ffmpeg-android-build
