name: Build FFmpeg for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout FFmpeg 7.0
      run: |
        git clone --depth=1 --branch n7.0 https://github.com/FFmpeg/FFmpeg.git ffmpeg

    - name: Setup NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
        unzip android-ndk-r26b-linux.zip
        export TOOLCHAIN=$PWD/android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64

    - name: Build FFmpeg
      run: |
        export TOOLCHAIN=$PWD/android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64
        cd ffmpeg
        ./configure \
          --prefix=$PWD/build \
          --target-os=android \
          --arch=arm64 \
          --cpu=armv8-a \
          --cross-prefix=$TOOLCHAIN/bin/aarch64-linux-android- \
          --cc=$TOOLCHAIN/bin/aarch64-linux-android21-clang \
          --enable-cross-compile \
          --disable-shared \
          --enable-static \
          --disable-doc \
          --disable-programs \
          --disable-libass \
          --enable-gpl \
          --enable-nonfree \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libvpx \
          --enable-librtmp \
          --enable-openssl \
          --enable-libfdk-aac \
          --enable-libmp3lame \
          --enable-libopus \
          --enable-libvorbis \
          --enable-pic \
          --enable-small \
          --extra-cflags="-march=armv8-a"
        make -j$(nproc)
        make install

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-android-arm64
        path: ffmpeg/build
