name: Build FFmpeg for Android ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config

    - name: Checkout FFmpeg
      run: |
        git clone --depth=1 --branch n7.0 https://github.com/FFmpeg/FFmpeg.git ffmpeg

    - name: Download and Extract Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
        unzip android-ndk-r26b-linux.zip
        echo "TOOLCHAIN=$(pwd)/android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV

    - name: Build libfdk-aac
      run: |
        git clone --depth=1 https://github.com/mstorsjo/fdk-aac.git
        cd fdk-aac
        ./autogen.sh
        ./configure --host=aarch64-linux-android --prefix=$(pwd)/build --disable-shared --enable-static \
          --with-sysroot=$TOOLCHAIN/sysroot \
          CC=$TOOLCHAIN/bin/aarch64-linux-android21-clang
        make -j$(nproc)
        make install
        echo "FDK_AAC_PATH=$(pwd)/build" >> $GITHUB_ENV

    - name: Build FFmpeg
      run: |
        cd ffmpeg
        ./configure \
          --prefix=$PWD/build \
          --target-os=android \
          --arch=arm64 \
          --cpu=armv8-a \
          --cross-prefix=$TOOLCHAIN/bin/aarch64-linux-android- \
          --cc=$TOOLCHAIN/bin/aarch64-linux-android21-clang \
          --enable-cross-compile \
          --disable-shared \
          --enable-static \
          --disable-doc \
          --disable-programs \
          --enable-gpl \
          --enable-nonfree \
          --enable-libfdk_aac \
          --extra-cflags="-I$FDK_AAC_PATH/include" \
          --extra-ldflags="-L$FDK_AAC_PATH/lib"
        make -j$(nproc)
        make install

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-android-arm64
        path: ffmpeg/build
