name: Build FFmpeg 7 for Android ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake build-essential cmake git libtool pkg-config \
          texinfo zlib1g-dev libssl-dev yasm nasm wget

    - name: Clone FFmpeg
      run: |
        git clone --branch n7.0 https://git.ffmpeg.org/ffmpeg.git ffmpeg

    - name: Clone Dependencies
      run: |
        mkdir deps && cd deps
        git clone https://github.com/mstorsjo/rtmpdump.git
        git clone https://code.videolan.org/videolan/x264.git/
        git clone https://bitbucket.org/multicoreware/x265_git.git
        git clone https://chromium.googlesource.com/webm/libvpx
        git clone https://aomedia.googlesource.com/aom
        git clone https://github.com/mstorsjo/fdk-aac.git
        git clone https://github.com/xiph/opus.git
        git clone https://github.com/tanersener/mobile-ffmpeg-lame.git mp3lame

    - name: Build Dependencies
      run: |
        cd deps
        cd rtmpdump/librtmp && make && sudo make install && cd ../..
        cd x264 && ./configure --enable-static && make -j$(nproc) && sudo make install && cd ..
        cd x265/build/linux && cmake -DCMAKE_BUILD_TYPE=Release ../../source && make -j$(nproc) && sudo make install && cd ../../..
        cd libvpx && ./configure --disable-examples --disable-unit-tests && make -j$(nproc) && sudo make install && cd ..
        cd aom && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF .. && make -j$(nproc) && sudo make install && cd ../..
        cd fdk-aac && autoreconf -fiv && ./configure --enable-static && make -j$(nproc) && sudo make install && cd ..
        cd opus && ./autogen.sh && ./configure --enable-static && make -j$(nproc) && sudo make install && cd ..
        cd mp3lame && ./configure --enable-static && make -j$(nproc) && sudo make install && cd ..

    - name: Build FFmpeg 7
      run: |
        cd ffmpeg
        ./configure \
          --prefix=$HOME/ffmpeg-android \
          --target-os=android \
          --arch=aarch64 \
          --cpu=armv8-a \
          --enable-cross-compile \
          --cross-prefix=aarch64-linux-android- \
          --enable-gpl \
          --enable-version3 \
          --enable-nonfree \
          --enable-static \
          --disable-shared \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libvpx \
          --enable-libaom \
          --enable-libmp3lame \
          --enable-libopus \
          --enable-libfdk_aac \
          --enable-librtmp \
          --enable-postproc \
          --enable-avfilter \
          --enable-openssl \
          --enable-pthreads \
          --enable-runtime-cpudetect \
          --enable-small \
          --disable-doc
        make -j$(nproc)
        make install

    - name: Upload FFmpeg Build
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg7-android-arm64
        path: ~/ffmpeg-android
