name: Build FFmpeg 7 for Android ARM64

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FFmpeg Maker
        uses: actions/checkout@v4
        with:
          repository: Javernaut/ffmpeg-android-maker
          ref: master
          path: ffmpeg-android-maker

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build FFmpeg
        working-directory: ffmpeg-android-maker
        run: |
          set -e # Exit immediately if a command fails
          # set -x # Uncomment for detailed command logging during debugging
          export ANDROID_SDK_HOME=$ANDROID_HOME
          export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
          ./ffmpeg-android-maker.sh

      - run: |
          pwd
          ls

      - name: Upload FFmpeg Build
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: ffmpeg7-android
          path: ./out