name: Build FFmpeg 7 for Android ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Clone FFmpeg Maker
      run: |
        git clone https://github.com/Javernaut/ffmpeg-android-maker.git
        cd ffmpeg-android-maker
        ./ffmpeg-android-maker.sh
        ll
    - name: Upload FFmpeg Build
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg7-android
        path: ~/out
